# Generated by Django 4.1 on 2022-09-04 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='Email',
        ),
    ]
