# Generated by Django 4.1 on 2022-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_rename_mail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
