# Generated by Django 4.1 on 2022-09-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_email_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attacht',
        ),
    ]
