# Generated by Django 4.1 on 2022-09-12 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_app', '0004_remove_email_attacht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(related_name='in_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
